# Generated by Django 5.1.6 on 2026-02-13 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("announcements", models.BooleanField(default=True)),
                ("assignments", models.BooleanField(default=True)),
                ("quizzes", models.BooleanField(default=True)),
                ("courses", models.BooleanField(default=True)),
                ("general", models.BooleanField(default=True)),
                ("sound", models.BooleanField(default=True)),
                ("vibration", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_settings",
            },
        ),
    ]
