# Generated by Django 5.1.6 on 2026-05-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("announcement", "Announcement"),
                    ("assignment", "Assignment"),
                    ("course", "Course Update"),
                    ("quiz", "Quiz"),
                    ("live_class", "Live Class"),
                    ("enrollment", "Enrollment"),
                    ("progress", "Progress"),
                    ("system", "System"),
                    ("message", "Message"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
