# Generated by Django 5.1.6 on 2026-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_classes", "0003_sessionbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveclass",
            name="recording_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
