# Generated by Django 5.1.6 on 2026-02-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_phone_verified_phoneotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="teacher_id",
            field=models.CharField(
                blank=True,
                help_text="5-digit unique ID for teachers",
                max_length=5,
                null=True,
                unique=True,
            ),
        ),
    ]
