# Generated by Django 5.1.6 on 2026-02-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_avatar",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL or ID of selected avatar",
                max_length=255,
            ),
        ),
    ]
