# Generated by Django 5.1.6 on 2026-02-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.CharField(
                blank=True,
                help_text="8-digit unique ID for students",
                max_length=8,
                null=True,
                unique=True,
            ),
        ),
    ]
