# Generated by Django 5.1.6 on 2026-03-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="parent_id",
            field=models.CharField(
                blank=True,
                help_text="6-digit unique ID for parents",
                max_length=6,
                null=True,
                unique=True,
            ),
        ),
    ]
