# Generated by Django 5.1.6 on 2026-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_parent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grade_level",
            field=models.CharField(
                blank=True,
                help_text="Grade or Class of the student (e.g., 10th Class)",
                max_length=50,
                null=True,
            ),
        ),
    ]
