# Generated by Django 5.1.15 on 2026-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_grade_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneotp",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
