export interface Quote {
    text: string;
    author: string;
}

export const DAILY_QUOTES: Quote[] = [
    { text: "Dream big. Start small. Act now.", author: "Robin Sharma" },
    { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { text: "Work hard in silence. Let success make the noise.", author: "Frank Ocean" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Great things never come from comfort zones.", author: "Roy T. Bennett" },
    { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
    { text: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Susan Johanson" },
    { text: "Little by little, a little becomes a lot.", author: "Tanzanian Proverb" },
    { text: "Strive for progress, not perfection.", author: "David Perlmutter" },
    { text: "Consistency beats intensity.", author: "Bruce Lee" },
    { text: "If it doesn’t challenge you, it won’t change you.", author: "Fred DeVito" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Don’t wish it were easier. Wish you were better.", author: "Jim Rohn" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
    { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
    { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { text: "A little progress each day adds up to big results.", author: "Satya Nani" },
    { text: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller Jr." },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
    { text: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
    { text: "Everything begins with an idea.", author: "Earl Nightingale" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { text: "Well done is better than well said.", author: "Benjamin Franklin" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb" },
    { text: "Success is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    { text: "Make each day your masterpiece.", author: "John Wooden" },
    { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
    { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
    { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
    { text: "Effort only fully releases its reward after a person refuses to quit.", author: "Napoleon Hill" },
    { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
    { text: "Small disciplines repeated with consistency lead to great achievements.", author: "John C. Maxwell" },
    { text: "The expert at anything was once a beginner.", author: "Helen Hayes" },
    { text: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain" },
    { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
    { text: "Nothing will work unless you do.", author: "Maya Angelou" },
    { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
    { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
    { text: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix" },
    { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    { text: "If opportunity doesn’t knock, build a door.", author: "Milton Berle" },
    { text: "You don’t have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
    { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
    { text: "Don’t limit your challenges. Challenge your limits.", author: "Jerry Dunn" },
    { text: "Your only competition is who you were yesterday.", author: "Kyle Chandler" },
    { text: "Winners are not afraid of losing.", author: "Robert Kiyosaki" },
    { text: "Be so good they can’t ignore you.", author: "Steve Martin" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "If you want to achieve greatness stop asking for permission.", author: "Brian Tracy" },
    { text: "You didn’t come this far to only come this far.", author: "Mick Kremling" },
    { text: "Excellence is a continuous process.", author: "A.P.J. Abdul Kalam" },
    { text: "Dream is not what you see in sleep, dream is something that does not let you sleep.", author: "A.P.J. Abdul Kalam" },
    { text: "Learning gives creativity, creativity leads to thinking, thinking provides knowledge, knowledge makes you great.", author: "A.P.J. Abdul Kalam" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "Knowledge is power.", author: "Francis Bacon" },
    { text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison" },
    { text: "Success is achieved and maintained by those who try and keep trying.", author: "W. Clement Stone" },
    { text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
    { text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" }
];
