# Generated by Django 5.1.6 on 2026-03-23 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.URLField(help_text="Category icon URL")),
            ],
            options={
                "verbose_name_plural": "Badge Categories",
                "db_table": "badge_categories",
            },
        ),
        migrations.CreateModel(
            name="AchievementBadge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(help_text="What this badge represents"),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("COMMON", "Common (Bronze)"),
                            ("RARE", "Rare (Silver)"),
                            ("EPIC", "Epic (Gold)"),
                            ("LEGENDARY", "Legendary (Diamond)"),
                            ("MYTHIC", "Mythic (Platinum)"),
                        ],
                        default="COMMON",
                        max_length=20,
                    ),
                ),
                ("icon_url", models.URLField(help_text="URL to badge icon image")),
                (
                    "animated_icon_url",
                    models.URLField(
                        blank=True, help_text="Optional animated version", null=True
                    ),
                ),
                (
                    "certificate_template",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "criteria_type",
                    models.CharField(
                        help_text="e.g., 'quiz_mastery', 'streak_master', 'course_completion'",
                        max_length=50,
                    ),
                ),
                (
                    "criteria_threshold",
                    models.IntegerField(help_text="Number of times/level required"),
                ),
                (
                    "tradeable",
                    models.BooleanField(
                        default=False, help_text="Can this badge be traded?"
                    ),
                ),
                (
                    "drop_rate",
                    models.FloatField(default=0.6, help_text="Relative rarity (0-1)"),
                ),
                ("total_awarded", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "achievement_badges",
                "ordering": ["-rarity", "name"],
                "indexes": [
                    models.Index(
                        fields=["rarity"], name="achievement_rarity_6cb680_idx"
                    ),
                    models.Index(
                        fields=["criteria_type"], name="achievement_criteri_667fba_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentBadge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current progress toward earning (e.g., 3/7 days)",
                    ),
                ),
                (
                    "is_claimed",
                    models.BooleanField(
                        default=False, help_text="Has student claimed this badge?"
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When badge was actually earned",
                        null=True,
                    ),
                ),
                ("is_tradeable", models.BooleanField(default=False)),
                (
                    "trade_status",
                    models.CharField(
                        choices=[
                            ("NOT_LISTED", "Not Listed"),
                            ("LISTED", "Listed for Trade"),
                            ("TRADED", "Already Traded"),
                        ],
                        default="NOT_LISTED",
                        max_length=20,
                    ),
                ),
                (
                    "showcase_on_profile",
                    models.BooleanField(
                        default=True, help_text="Show on public profile?"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_badges",
                        to="progress.achievementbadge",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_badges",
                "ordering": ["-awarded_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-awarded_at"],
                        name="student_bad_student_36ba7a_idx",
                    ),
                    models.Index(
                        fields=["is_claimed"], name="student_bad_is_clai_a66c97_idx"
                    ),
                ],
                "unique_together": {("student", "badge")},
            },
        ),
    ]
