# Generated by Django 5.1.6 on 2026-03-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_badgecategory_achievementbadge_studentbadge"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentbadge",
            name="certificate_url",
            field=models.URLField(
                blank=True, help_text="Generated certificate URL", null=True
            ),
        ),
    ]
