# Generated by Django 5.1.6 on 2026-02-20 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("foundational", "Foundational"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=50,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_concepts",
                        to="intelligence.concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concept",
                "verbose_name_plural": "Concepts",
                "db_table": "intelligence_concepts",
            },
        ),
        migrations.CreateModel(
            name="AcademicRisk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("risk_percentage", models.FloatField(default=0.0)),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("silent_disengagement", models.BooleanField(default=False)),
                ("performance_decline", models.BooleanField(default=False)),
                ("intervention_plan", models.TextField(blank=True, default="")),
                ("is_alert_sent", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Risk",
                "verbose_name_plural": "Academic Risks",
                "db_table": "intelligence_academic_risks",
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="MomentumScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("score", models.PositiveIntegerField(default=50)),
                ("daily_change", models.IntegerField(default=0)),
                ("weekly_change", models.IntegerField(default=0)),
                ("attendance_consistency", models.FloatField(default=0.0)),
                ("practice_frequency", models.FloatField(default=0.0)),
                ("score_improvement_trend", models.FloatField(default=0.0)),
                ("focus_behavior", models.FloatField(default=0.0)),
                ("revision_consistency", models.FloatField(default=0.0)),
                (
                    "rank_comparison",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("suggestions", models.JSONField(default=list)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="momentum_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Momentum Score",
                "verbose_name_plural": "Momentum Scores",
                "db_table": "intelligence_momentum_scores",
                "ordering": ["-date"],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="StudentGenome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mastery_percentage", models.FloatField(default=0.0)),
                ("speed_ratio", models.FloatField(default=1.0)),
                ("accuracy_ratio", models.FloatField(default=0.0)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("revision_consistency", models.FloatField(default=0.0)),
                (
                    "weak_clusters",
                    models.JSONField(default=dict, help_text="Clusters of weak areas"),
                ),
                (
                    "behavior_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g., Fast Leaner, Deep Diver, Cautious",
                        max_length=100,
                    ),
                ),
                ("improvement_strategy", models.TextField(blank=True, default="")),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_stats",
                        to="intelligence.concept",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genome_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Genome",
                "verbose_name_plural": "Student Genomes",
                "db_table": "intelligence_student_genome",
                "unique_together": {("student", "concept")},
            },
        ),
    ]
