# Generated by Django 5.1.6 on 2026-02-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
        ("quizzes", "0003_remove_quizquestion_concept"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concept",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="studentgenome",
            name="concept",
        ),
        migrations.AlterUniqueTogether(
            name="momentumscore",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="momentumscore",
            name="student",
        ),
        migrations.AlterUniqueTogether(
            name="studentgenome",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentgenome",
            name="student",
        ),
        migrations.DeleteModel(
            name="AcademicRisk",
        ),
        migrations.DeleteModel(
            name="Concept",
        ),
        migrations.DeleteModel(
            name="MomentumScore",
        ),
        migrations.DeleteModel(
            name="StudentGenome",
        ),
    ]
