# Generated by Django 5.1.6 on 2026-03-23 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receive_weekly_reports", models.BooleanField(default=True)),
                ("receive_immediate_alerts", models.BooleanField(default=True)),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "student"},
                        related_name="parents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Account",
                "verbose_name_plural": "Parent Accounts",
                "db_table": "parent_accounts",
            },
        ),
        migrations.CreateModel(
            name="WeeklyProgressReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("quizzes_completed", models.PositiveIntegerField(default=0)),
                ("average_quiz_score", models.FloatField(default=0.0)),
                ("lessons_watched", models.PositiveIntegerField(default=0)),
                ("badges_earned", models.PositiveIntegerField(default=0)),
                (
                    "attendance_rate",
                    models.FloatField(
                        default=0.0, help_text="Percentage of live classes attended"
                    ),
                ),
                ("time_spent_seconds", models.PositiveBigIntegerField(default=0)),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated textual summary of the week",
                    ),
                ),
                (
                    "teacher_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Aggregated notes from teachers during the week",
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "report_pdf_url",
                    models.URLField(
                        blank=True, default="", help_text="URL to generated PDF report"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_reports",
                        to="parents.parentaccount",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weekly_progress_reports",
                "ordering": ["-week_end_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentLinkRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_requests",
                        to="parents.parentaccount",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_link_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_link_requests",
                "unique_together": {("parent", "student")},
            },
        ),
    ]
