# Generated by Django 5.1.6 on 2026-02-20 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quiz_questions",
                to="intelligence.concept",
            ),
        ),
    ]
