# Generated by Django 5.1.6 on 2026-02-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quizquestion_concept"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="concept",
        ),
    ]
