# Generated by Django 5.1.6 on 2026-02-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_remove_quizquestion_concept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="correct_answer",
            field=models.CharField(
                help_text='The correct option(s), e.g., "a" or "a,b,c"', max_length=15
            ),
        ),
    ]
