# Generated by Django 5.2.5 on 2026-02-22
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=255)),
                ('cards_generated', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_flashcard_sessions',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['student', '-created_at'], name='aiflash_student_created_idx'),
                    models.Index(fields=['topic'], name='aiflash_topic_idx'),
                ],
            },
        ),
    ]
