# Generated by Django 5.1.6 on 2026-02-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tutor", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="flashcardsession",
            new_name="ai_flashcar_student_6c019a_idx",
            old_name="aiflash_student_created_idx",
        ),
        migrations.RenameIndex(
            model_name="flashcardsession",
            new_name="ai_flashcar_topic_c887f0_idx",
            old_name="aiflash_topic_idx",
        ),
    ]
