# Generated by Django 5.1.6 on 2026-03-31 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_tutor",
            "0002_rename_aiflash_student_created_idx_ai_flashcar_student_6c019a_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CognitiveState",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frustration_score",
                    models.FloatField(
                        default=0.0, help_text="0.0 = calm, 1.0 = very frustrated"
                    ),
                ),
                (
                    "engagement_score",
                    models.FloatField(
                        default=0.5, help_text="0.0 = disengaged, 1.0 = deeply engaged"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5, help_text="0.0 = uncertain, 1.0 = very confident"
                    ),
                ),
                (
                    "cognitive_load",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("overloaded", "Overloaded"),
                        ],
                        default="medium",
                        max_length=12,
                    ),
                ),
                (
                    "current_mood",
                    models.CharField(
                        choices=[
                            ("focused", "Focused"),
                            ("neutral", "Neutral"),
                            ("struggling", "Struggling"),
                            ("frustrated", "Frustrated"),
                            ("bored", "Bored"),
                            ("confident", "Confident"),
                        ],
                        default="neutral",
                        max_length=12,
                    ),
                ),
                (
                    "last_signals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw signal breakdown used to compute scores",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "last_adaptation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Last adaptation strategy: tone, difficulty_adjustment, etc.",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cognitive_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_cognitive_states",
                "indexes": [
                    models.Index(
                        fields=["current_mood"], name="ai_cognitiv_current_0f64a6_idx"
                    ),
                    models.Index(
                        fields=["frustration_score"],
                        name="ai_cognitiv_frustra_1b6929_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CognitiveStateHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("avg_frustration", models.FloatField(default=0.0)),
                ("avg_engagement", models.FloatField(default=0.5)),
                ("avg_confidence", models.FloatField(default=0.5)),
                ("dominant_mood", models.CharField(default="neutral", max_length=12)),
                ("total_interaction_events", models.PositiveIntegerField(default=0)),
                ("total_session_minutes", models.PositiveIntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cognitive_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_cognitive_state_history",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["student", "-date"],
                        name="ai_cognitiv_student_e535ef_idx",
                    )
                ],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="InteractionEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Groups events within a single study session",
                        max_length=64,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("typing_pattern", "Typing Pattern"),
                            ("touch_pattern", "Touch Pattern"),
                            ("mouse_pattern", "Mouse Pattern"),
                            ("quiz_interaction", "Quiz Interaction"),
                            ("scroll_pattern", "Scroll Pattern"),
                            ("focus_pattern", "Focus/Attention Pattern"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("mobile", "Mobile (Expo)"), ("web", "Web (React)")],
                        max_length=10,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Aggregated interaction metrics: typing_speed_wpm, backspace_rate, pause_count, scroll_velocity, tap_frequency, idle_seconds, etc.",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Current screen, lesson_id, quiz_id, etc.",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_interaction_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-created_at"],
                        name="ai_interact_student_ff230b_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="ai_interact_session_871cd8_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="ai_interact_event_t_3ccb94_idx"
                    ),
                    models.Index(
                        fields=["student", "session_id"],
                        name="ai_interact_student_cbdecf_idx",
                    ),
                ],
            },
        ),
    ]
