# Generated by Django 5.1.6 on 2026-02-24 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PremiumPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        help_text="Plan tier (basic / pro / enterprise)",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name, e.g. "MentiQ Basic"', max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short description of the plan",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Monthly price in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Annual price in USD (discounted)",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "max_courses",
                    models.IntegerField(
                        default=5,
                        help_text="Max courses a user can enroll in (-1 = unlimited)",
                    ),
                ),
                (
                    "max_downloads",
                    models.IntegerField(
                        default=10, help_text="Max downloads per month (-1 = unlimited)"
                    ),
                ),
                (
                    "ai_tutor_access",
                    models.BooleanField(
                        default=False, help_text="Access to AI tutor feature"
                    ),
                ),
                (
                    "live_classes_access",
                    models.BooleanField(
                        default=False, help_text="Access to live classes"
                    ),
                ),
                (
                    "certificate_access",
                    models.BooleanField(
                        default=False, help_text="Can get completion certificates"
                    ),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False, help_text="Priority support access"
                    ),
                ),
                (
                    "analytics_access",
                    models.BooleanField(
                        default=False, help_text="Advanced analytics dashboard"
                    ),
                ),
                (
                    "custom_features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional custom features as a list of strings",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is currently available",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, help_text="Highlight as most popular plan"
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Badge text, e.g. "Most Popular", "Best Value"',
                        max_length=30,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#7c3aed",
                        help_text="Accent color hex for the plan card",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "premium_plans",
                "ordering": ["price"],
            },
        ),
    ]
