# Generated by Django 5.1.6 on 2026-02-24 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_add_premium_plan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="premiumplan",
            options={"ordering": ["quarterly_price"]},
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="price",
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="quarterly_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Quarterly price in INR",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="annual_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Annual price in INR (discounted)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
        migrations.CreateModel(
            name="SchoolSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("quarterly", "Quarterly"), ("annual", "Annual")],
                        default="annual",
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="admin_panel.premiumplan",
                    ),
                ),
            ],
            options={
                "db_table": "school_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
