# Generated by Django 5.1.6 on 2026-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_update_premium_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                    ("custom", "Custom"),
                ],
                help_text="Plan tier (pro / enterprise / custom)",
                max_length=12,
                unique=True,
            ),
        ),
    ]
