# Generated by Django 5.1.6 on 2026-03-23 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0003_remove_offlinedownload_micro_lesson_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MicroLesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compressed_video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL of the compressed video (typically Cloudinary).",
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Distilled text summary of the lesson content.",
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        default=0, help_text="Size of the compressed video in bytes."
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Duration of the compressed video in seconds.",
                    ),
                ),
                (
                    "compression_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "compression_ratio",
                    models.FloatField(
                        default=0.0,
                        help_text="Ratio of compressed size to original size (e.g. 0.35 = 35%).",
                    ),
                ),
                (
                    "original_video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL of the original (full-quality) video.",
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        help_text="The parent lesson this micro-lesson is derived from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="micro_lesson",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Micro Lesson",
                "verbose_name_plural": "Micro Lessons",
                "db_table": "micro_lessons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineDownload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "download_status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("downloading", "Downloading"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the download was completed on device.",
                        null=True,
                    ),
                ),
                (
                    "progress_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Lesson completion progress tracked offline (0-100).",
                    ),
                ),
                (
                    "last_position_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Last playback position in the video (for resume).",
                    ),
                ),
                (
                    "is_lesson_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the student completed the lesson offline.",
                    ),
                ),
                (
                    "completed_at_offline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of offline completion (synced later).",
                        null=True,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this record synced with the server.",
                        null=True,
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Device identifier for multi-device support.",
                        max_length=255,
                    ),
                ),
                (
                    "micro_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="offline.microlesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Download",
                "verbose_name_plural": "Offline Downloads",
                "db_table": "offline_downloads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "download_status"],
                        name="offline_dow_student_d8d1ac_idx",
                    ),
                    models.Index(
                        fields=["micro_lesson", "download_status"],
                        name="offline_dow_micro_l_4f3cde_idx",
                    ),
                ],
                "unique_together": {("student", "micro_lesson")},
            },
        ),
    ]
