# Generated by Django 5.1.6 on 2026-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("technology", "Technology"),
                    ("business", "Business"),
                    ("art", "Art"),
                    ("science", "Science"),
                    ("mathematics", "Mathematics"),
                    ("english", "English"),
                    ("history", "History"),
                    ("computer_science", "Computer Science"),
                    ("physics", "Physics"),
                    ("chemistry", "Chemistry"),
                    ("biology", "Biology"),
                    ("arts", "Arts"),
                    ("music", "Music"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=50,
            ),
        ),
    ]
