# Generated by Django 5.1.6 on 2026-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_coursereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="grade_level",
            field=models.CharField(
                blank=True,
                help_text="Target grade or class for this course (e.g., 10th Class)",
                max_length=50,
                null=True,
            ),
        ),
    ]
