# Generated by Django 5.1.6 on 2026-02-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
        ("courses", "0003_coursereview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="created_by_admin",
            field=models.BooleanField(
                default=False,
                help_text="True if created by admin rather than a teacher",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("all", "Everyone"),
                    ("students", "Students Only"),
                    ("teachers", "Teachers Only"),
                ],
                default="all",
                help_text="Who can see this announcement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="The author. Null for admin-created announcements.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["target_audience", "-created_at"],
                name="announcemen_target__40eb96_idx",
            ),
        ),
    ]
