# Generated by Django 5.1.6 on 2026-02-25 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_add_target_audience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="target_student",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this is a personal announcement for this student only.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
