# Generated by Django 5.1.6 on 2026-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_add_target_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("all", "Everyone"),
                    ("students", "Students Only"),
                    ("teachers", "Teachers Only"),
                    ("parents", "Parents Only"),
                ],
                default="all",
                help_text="Who can see this announcement",
                max_length=10,
            ),
        ),
    ]
