# Generated by Django 5.1.6 on 2026-03-23 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MicroLesson",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("low", "Low (144p, ~5MB)"),
                            ("medium", "Medium (360p, ~15MB)"),
                            ("high", "High (720p, ~50MB)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "compression_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Compression"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "compressed_video_url",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary URL for compressed video",
                        null=True,
                    ),
                ),
                (
                    "compressed_video_size",
                    models.PositiveIntegerField(default=0, help_text="File size in MB"),
                ),
                (
                    "compressed_pdf_url",
                    models.URLField(
                        blank=True, help_text="Compressed PDF attachment", null=True
                    ),
                ),
                (
                    "original_duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Original video duration in seconds"
                    ),
                ),
                (
                    "compressed_duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Compressed video duration in seconds"
                    ),
                ),
                (
                    "compression_ratio",
                    models.FloatField(
                        default=0.0, help_text="Compression ratio achieved"
                    ),
                ),
                ("total_downloads", models.PositiveIntegerField(default=0)),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="micro_lessons",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "micro_lessons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineDownload",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("downloading", "Downloading"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "downloaded_file_url",
                    models.URLField(
                        blank=True, help_text="Local device storage URL", null=True
                    ),
                ),
                ("file_size_mb", models.FloatField(default=0.0)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When offline access expires"),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_expired", models.BooleanField(db_index=True, default=False)),
                (
                    "download_progress",
                    models.FloatField(
                        default=0.0, help_text="Download progress percentage (0-100)"
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mobile device identifier",
                        max_length=255,
                    ),
                ),
                (
                    "wifi_only",
                    models.BooleanField(
                        default=True, help_text="Only download over WiFi"
                    ),
                ),
                (
                    "micro_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="lessons.microlesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "offline_downloads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="microlesson",
            index=models.Index(
                fields=["lesson", "compression_status"],
                name="micro_lesso_lesson__b684a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="microlesson",
            index=models.Index(
                fields=["quality", "compression_status"],
                name="micro_lesso_quality_23ed14_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinedownload",
            index=models.Index(
                fields=["student", "status"], name="offline_dow_student_866424_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinedownload",
            index=models.Index(
                fields=["student", "is_expired"], name="offline_dow_student_41ff95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinedownload",
            index=models.Index(
                fields=["expires_at"], name="offline_dow_expires_15b1f9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offlinedownload",
            unique_together={("student", "micro_lesson")},
        ),
    ]
