# Generated by Django 5.1.6 on 2026-03-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_microlesson_offlinedownload_and_more"),
    ]

    operations = [
    ]
