# Generated by Django 5.1.6 on 2026-03-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_remove_offlinedownload_micro_lesson_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="offlinedownload",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="offlinedownload",
            name="micro_lesson",
        ),
        migrations.RemoveField(
            model_name="offlinedownload",
            name="student",
        ),
        migrations.DeleteModel(
            name="MicroLesson",
        ),
        migrations.DeleteModel(
            name="OfflineDownload",
        ),
    ]
